spring:
  profiles:
    active: green
    group:
      local: local, common, secret
      blue: blue, common, secret
      green: green, common, secret

server:
  env: green
---

spring:
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      client:
        registration:
          naver:
            redirectUri: http://localhost:8080/login/oauth2/code/naver
          kakao:
            redirectUri: http://localhost:8080/login/oauth2/code/kakao
server:
  port: 8080
  serverAddress: localhost

serverName: local_server

client:
  address: http://localhost:3000

---

spring:
  config:
    activate:
      on-profile: blue
  security:
    oauth2:
      client:
        registration:
          naver:
            redirectUri: http://15.165.96.196/login/oauth2/code/naver
          kakao:
            redirectUri: http://15.165.96.196/login/oauth2/code/kakao
server:
  port: 8080
  serverAddress: 15.165.96.196

serverName: blue_server

client:
  address: https://d2rbwqvcx2p2xt.cloudfront.net

---

spring:
  config:
    activate:
      on-profile: green
  security:
    oauth2:
      client:
        registration:
          naver:
            redirectUri: http://15.165.96.196/login/oauth2/code/naver
          kakao:
            redirectUri: http://15.165.96.196/login/oauth2/code/kakao
server:
  port: 9090
  serverAddress: 15.165.96.196

serverName: green_server

client:
  address: https://d2rbwqvcx2p2xt.cloudfront.net
---

spring:
  config:
    activate:
      on-profile: common

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis:
  mapper-locations:
    - mappers/*.xml
    - mappers/user/*.xml

---

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
